### ISSUE TITLE
这个可以单机多卡训练吗？

### ISSUE THREAD

**Issue by wenninghui** [yangjianxin1/OFA-Chinese#6]

**Comment by yangjianxin1** [comment]
可以单机多卡训练，通过CUDA_VISIBLE_DEVICES设置用哪些卡训练，例如使用0和1卡：`CUDA_VISIBLE_DEVICES=0,1 python train.py --train_args_file train_args/train_ofa.json
`

**Comment by wenninghui** [comment]
谢谢指导！刚试了一下，有如下报错，烦请再指导一下，谢谢~

**Comment by yangjianxin1** [comment]
你的回复里貌似没有看到报错信息

**Comment by wenninghui** [comment]
不好意思，可能图片发不出去，我复制成文字


Traceback (most recent call last):
  File "train.py", line 84, in <module>
    main()
  File "train.py", line 67, in main
    train_result = trainer.train()
  File "/data2/anaconda3/envs/image_caption/lib/python3.8/site-packages/transformers/trainer.py", line 1409, in train
    return inner_training_loop(
  File "/data2/anaconda3/envs/image_caption/lib/python3.8/site-packages/transformers/trainer.py", line 1651, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/data2/anaconda3/envs/image_caption/lib/python3.8/site-packages/transformers/trainer.py", line 2345, in training_step
    loss = self.compute_loss(model, inputs)
  File "/data2/anaconda3/envs/image_caption/lib/python3.8/site-packages/transformers/trainer.py", line 2377, in compute_loss
    outputs = model(**inputs)
  File "/data2/anaconda3/envs/image_caption/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data2/anaconda3/envs/image_caption/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 171, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/data2/anaconda3/envs/image_caption/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 181, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/data2/anaconda3/envs/image_caption/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 89, in parallel_apply
    output.reraise()
  File "/data2/anaconda3/envs/image_caption/lib/python3.8/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/data2/anaconda3/envs/image_caption/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 64, in _worker
    output = module(*input, **kwargs)
  File "/data2/anaconda3/envs/image_caption/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data3/github/OFA-Chinese/component/ofa/modeling_ofa.py", line 2105, in forward
    decoder_outputs = self.decoder(
  File "/data2/anaconda3/envs/image_caption/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data3/github/OFA-Chinese/component/ofa/modeling_ofa.py", line 1671, in forward
    attention_mask = self._prepare_decoder_attention_mask(attention_mask, shape, dtype, past_key_values_length)
  File "/data3/github/OFA-Chinese/component/ofa/modeling_ofa.py", line 1506, in _prepare_decoder_attention_mask
    expanded_attn_mask if combined_attention_mask is None else expanded_attn_mask + combined_attention_mask
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

  0%|                                                                           | 0/80 [00:49<?, ?it/s]
